// import library
@Library('voxelcloud-jenkins-lib') _

node {
    label 'model-scm'
    
    def additionalInfo = ''

    try {
        /*
        Checkout and build front end
        */
        stage('Checkout') {
            // checkout default repository for this build
            checkoutRepo('RetinaPtWechat')
        }

        // build front end
        stage('Install') {
            nodejs('nodejs12.18') {
                sh 'yarn global add expo-cli'
                sh 'yarn run build'
                }
        }

        def buildName = getBuildName()
        def webServerDockerImageName = "voxelcloud/retina-wechat-client:${buildName}"
        def dockerImageWebServer
        stage('Build-Frontend') {
            dockerImageWebServer = buildDockerImage(webServerDockerImageName)
        }

        // publish docker images
        stage('Publish-Image') {
            pushDockerImage(dockerImageWebServer)
        }

        additionalInfo = "Docker Images: ${webServerDockerImageName}"
    } catch (e) {
        currentBuild.result = "FAILED"
        throw e
    } finally {
        // send email to notify developers
        notifyBuild(currentBuild.result == 'FAILED' ? '' : additionalInfo)
    }
}